name: 'Dependency Review'

on:
  pull_request:
    branches:
      - '**'

permissions:
  id-token: write
  contents: read

jobs:
  dependency-review:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout Repository'
        uses: actions/checkout@v3
      - name: 'Dependency Review'
        uses: actions/dependency-review-action@v2
